apiVersion: v1
kind: Config
current-context: {cluster}
contexts:
- name: {cluster}
  context:
    cluster: {cluster}
    user: devops-cluster-admin

clusters:
- name: {cluster}
  cluster:
    certificate-authority-data: {cluster_certs}
    server: https://127.0.0.1:11962
users:
- name: devops-cluster-admin
  user:
    token: {token}